// IOS DEPLOY
export const GET_IOS_DEPLOY_INFO = 'GET_IOS_DEPLOY_INFO';
export const GET_IOS_DEPLOY_INFO_SUCCESS = 'GET_IOS_DEPLOY_INFO_SUCCESS';
export const GET_IOS_DEPLOY_INFO_FAIL = 'GET_IOS_DEPLOY_INFO_FAIL';

// IOS DEVICE
export const GET_IOS_DEVICE_INFO = 'GET_IOS_DEVICE_INFO';
export const GET_IOS_DEVICE_INFO_SUCCESS = 'GET_IOS_DEVICE_INFO_SUCCESS';
export const GET_IOS_DEVICE_INFO_FAIL = 'GET_IOS_DEVICE_FAIL';

// XCODEBUILD
export const GET_XCODEBUILD_INFO = 'GET_XCODEBUILD_INFO';
export const GET_XCODEBUILD_INFO_SUCCESS = 'GET_XCODEBUILD_INFO_SUCCESS';
export const GET_XCODEBUILD_INFO_FAIL = 'GET_XCODEBUILD_INFO_FAIL';

// SOCKET
export const SET_SOCKET_CONNECTION = 'SET_SOCKET_CONNECTION';