export const GET_IOS_DEPLOY_INFO = 'GET_IOS_DEPLOY_INFO';
export const GET_IOS_DEPLOY_INFO_SUCCESS = 'GET_IOS_DEPLOY_INFO_SUCCESS';
export const GET_IOS_DEPLOY_INFO_FAIL = 'GET_IOS_DEPLOY_INFO_FAIL';

export const SET_SOCKET_CONNECTION = 'SET_SOCKET_CONNECTION';